{
 "title": "Qms",
 "time": { "from": "now-30m", "to": "now" },
 "refresh": "10s",
 "templating": {
  "list": [
   {
    "name": "handles",
    "query": "/check_auth,  /ping,  /client/get_user, /client/register, /client/update_user,  /client/login, /client/check_unique_user,  /admin/create_organization, /admin/update_organization, /admin/get_organizations_list, /client/fetch_organization,  /admin/create_service, /admin/update_service, /admin/remove_service, /admin/generate_qr, /client/enter_queue, /admin/queue_tickets, /admin/add_user, /admin/remove_user, /admin/update_user_privilege, /client/get_current_queue_info"
   }
  ]
 },
 "panels": [
  { "title": "Performance", "type": "row", "gridPos": { "h": 1, "w": 24, "x": 0, "y": 0 } },
  {
   "title": "RPS",
   "type": "graph",
   "gridPos": { "h": 8, "w": 12, "x": 0, "y": 1 },
   "yaxes": [
    { "format": "short" }
   ],
   "targets": [
    {
     "expr": "sum by (instance) ( rate(starlette_requests_total{path_template !~ '/metrics.*'}[$__interval]))"
    }
   ]
  },
  {
   "title": "CPU Usage",
   "type": "graph",
   "gridPos": { "h": 8, "w": 12, "x": 12, "y": 1 },
   "yaxes": [
    { "format": "short" }
   ],
   "targets": [
    {
     "expr": "rate(process_cpu_seconds_total{job!=\"prometheus\"}[$__interval])"
    }
   ]
  },
  {
   "title": "Latency",
   "type": "graph",
   "gridPos": { "h": 8, "w": 12, "x": 0, "y": 9 },
   "yaxes": [
    { "format": "short" }
   ],
   "targets": [
    {
     "expr": "histogram_quantile(0.95, sum(rate(starlette_requests_processing_time_seconds_bucket{path_template!~\"/metrics.*\"}\n[$__interval])) by (le))",
     "legendFormat": "0.95"
    },
    {
     "expr": "histogram_quantile(0.70, sum(rate(starlette_requests_processing_time_seconds_bucket{path_template!~\"/metrics.*\"}\n[$__interval])) by (le))",
     "legendFormat": "0.7"
    }
   ]
  },
  { "title": "Row title", "type": "row", "gridPos": { "h": 1, "w": 24, "x": 0, "y": 17 } },
  {
   "title": "Total http codes",
   "type": "graph",
   "gridPos": { "h": 10, "w": 24, "x": 0, "y": 18 },
   "yaxes": [
    { "format": "short" }
   ],
   "targets": [
    {
     "expr": "sum(rate(starlette_responses_total{job=\"qms\"}[$__interval])) by (status_code)"
    }
   ]
  },
  {
   "title": "[[handles]] http codes",
   "type": "graph",
   "gridPos": { "h": 8, "w": 12, "x": 0, "y": 27 },
   "repeat": "handles",
   "yaxes": [
    { "format": "short" }
   ],
   "targets": [
    {
     "expr": "sum(rate(starlette_responses_total{job=\"qms\", path_template=\"[[handles]]\"}[$__interval])) by (status_code)"
    }
   ]
  },
  {
   "title": "/admin/generate_qr http codes",
   "type": "graph",
   "gridPos": { "h": 8, "w": 12, "x": 0, "y": 28 },
   "yaxes": [
    { "format": "short" }
   ],
   "targets": [
    {
     "expr": "sum(rate(starlette_responses_total{job=\"qms\", path_template=\"/admin/generate_qr\"}[1m])) by (status_code)"
    }
   ]
  },
  {
   "title": "/admin/create_service http codes",
   "type": "graph",
   "gridPos": { "h": 8, "w": 12, "x": 0, "y": 28 },
   "yaxes": [
    { "format": "short" }
   ],
   "targets": [
    {
     "expr": "sum(rate(starlette_responses_total{job=\"qms\", path_template=\"/admin/create_service\"}[1m])) by (status_code)"
    }
   ]
  },
  {
   "title": "/admin/update_organization http codes",
   "type": "graph",
   "gridPos": { "h": 8, "w": 12, "x": 0, "y": 28 },
   "yaxes": [
    { "format": "short" }
   ],
   "targets": [
    {
     "expr": "sum(rate(starlette_responses_total{job=\"qms\", path_template=\"/admin/update_organization\"}[1m])) by (status_code)"
    }
   ]
  },
  {
   "title": "/client/update_user http codes",
   "type": "graph",
   "gridPos": { "h": 8, "w": 12, "x": 0, "y": 28 },
   "yaxes": [
    { "format": "short" }
   ],
   "targets": [
    {
     "expr": "sum(rate(starlette_responses_total{job=\"qms\", path_template=\"/client/update_user\"}[1m])) by (status_code)"
    }
   ]
  },
  {
   "title": "/client/get_user http codes",
   "type": "graph",
   "gridPos": { "h": 8, "w": 12, "x": 0, "y": 28 },
   "yaxes": [
    { "format": "short" }
   ],
   "targets": [
    {
     "expr": "sum(rate(starlette_responses_total{job=\"qms\", path_template=\"/client/get_user\"}[1m])) by (status_code)"
    }
   ]
  },
  {
   "title": "/client/login http codes",
   "type": "graph",
   "gridPos": { "h": 8, "w": 12, "x": 0, "y": 28 },
   "yaxes": [
    { "format": "short" }
   ],
   "targets": [
    {
     "expr": "sum(rate(starlette_responses_total{job=\"qms\", path_template=\"/client/login\"}[1m])) by (status_code)"
    }
   ]
  },
  {
   "title": "/client/register http codes",
   "type": "graph",
   "gridPos": { "h": 8, "w": 12, "x": 0, "y": 28 },
   "yaxes": [
    { "format": "short" }
   ],
   "targets": [
    {
     "expr": "sum(rate(starlette_responses_total{job=\"qms\", path_template=\"/client/register\"}[$__interval])) by (status_code)"
    }
   ]
  },
  {
   "title": "[[handles]] timings",
   "type": "graph",
   "gridPos": { "h": 8, "w": 12, "x": 12, "y": 28 },
   "repeat": "handles",
   "yaxes": [
    { "format": "short" }
   ],
   "targets": [
    {
     "expr": "histogram_quantile(0.95, sum(rate(starlette_requests_processing_time_seconds_bucket{job=\"qms\", path_template=\"[[handles]]\"}[$__interval])) by (le))"
    }
   ]
  },
  {
   "title": "[[handles]] http codes",
   "type": "graph",
   "gridPos": { "h": 8, "w": 12, "x": 0, "y": 36 },
   "yaxes": [
    { "format": "short" }
   ],
   "targets": [
    {
     "expr": "sum(rate(starlette_responses_total{job=\"qms\", path_template=\"[[handles]]\"}[$__interval])) by (status_code)"
    }
   ]
  },
  {
   "title": "[[handles]] timings",
   "type": "graph",
   "gridPos": { "h": 8, "w": 12, "x": 12, "y": 36 },
   "yaxes": [
    { "format": "short" }
   ],
   "targets": [
    {
     "expr": "histogram_quantile(0.95, sum(rate(starlette_requests_processing_time_seconds_bucket{job=\"qms\", path_template=\"[[handles]]\"}[$__interval])) by (le))"
    }
   ]
  },
  {
   "title": "[[handles]] http codes",
   "type": "graph",
   "gridPos": { "h": 8, "w": 12, "x": 0, "y": 44 },
   "yaxes": [
    { "format": "short" }
   ],
   "targets": [
    {
     "expr": "sum(rate(starlette_responses_total{job=\"qms\", path_template=\"[[handles]]\"}[$__interval])) by (status_code)"
    }
   ]
  },
  {
   "title": "[[handles]] timings",
   "type": "graph",
   "gridPos": { "h": 8, "w": 12, "x": 12, "y": 44 },
   "yaxes": [
    { "format": "short" }
   ],
   "targets": [
    {
     "expr": "histogram_quantile(0.95, sum(rate(starlette_requests_processing_time_seconds_bucket{job=\"qms\", path_template=\"[[handles]]\"}[$__interval])) by (le))"
    }
   ]
  },
  {
   "title": "[[handles]] http codes",
   "type": "graph",
   "gridPos": { "h": 8, "w": 12, "x": 0, "y": 52 },
   "yaxes": [
    { "format": "short" }
   ],
   "targets": [
    {
     "expr": "sum(rate(starlette_responses_total{job=\"qms\", path_template=\"[[handles]]\"}[$__interval])) by (status_code)"
    }
   ]
  },
  {
   "title": "[[handles]] timings",
   "type": "graph",
   "gridPos": { "h": 8, "w": 12, "x": 12, "y": 52 },
   "yaxes": [
    { "format": "short" }
   ],
   "targets": [
    {
     "expr": "histogram_quantile(0.95, sum(rate(starlette_requests_processing_time_seconds_bucket{job=\"qms\", path_template=\"[[handles]]\"}[$__interval])) by (le))"
    }
   ]
  },
  {
   "title": "[[handles]] http codes",
   "type": "graph",
   "gridPos": { "h": 8, "w": 12, "x": 0, "y": 60 },
   "yaxes": [
    { "format": "short" }
   ],
   "targets": [
    {
     "expr": "sum(rate(starlette_responses_total{job=\"qms\", path_template=\"[[handles]]\"}[$__interval])) by (status_code)"
    }
   ]
  },
  {
   "title": "[[handles]] timings",
   "type": "graph",
   "gridPos": { "h": 8, "w": 12, "x": 12, "y": 60 },
   "yaxes": [
    { "format": "short" }
   ],
   "targets": [
    {
     "expr": "histogram_quantile(0.95, sum(rate(starlette_requests_processing_time_seconds_bucket{job=\"qms\", path_template=\"[[handles]]\"}[$__interval])) by (le))"
    }
   ]
  },
  {
   "title": "[[handles]] http codes",
   "type": "graph",
   "gridPos": { "h": 8, "w": 12, "x": 0, "y": 68 },
   "yaxes": [
    { "format": "short" }
   ],
   "targets": [
    {
     "expr": "sum(rate(starlette_responses_total{job=\"qms\", path_template=\"[[handles]]\"}[$__interval])) by (status_code)"
    }
   ]
  },
  {
   "title": "[[handles]] timings",
   "type": "graph",
   "gridPos": { "h": 8, "w": 12, "x": 12, "y": 68 },
   "yaxes": [
    { "format": "short" }
   ],
   "targets": [
    {
     "expr": "histogram_quantile(0.95, sum(rate(starlette_requests_processing_time_seconds_bucket{job=\"qms\", path_template=\"[[handles]]\"}[$__interval])) by (le))"
    }
   ]
  },
  {
   "title": "[[handles]] http codes",
   "type": "graph",
   "gridPos": { "h": 8, "w": 12, "x": 0, "y": 76 },
   "yaxes": [
    { "format": "short" }
   ],
   "targets": [
    {
     "expr": "sum(rate(starlette_responses_total{job=\"qms\", path_template=\"[[handles]]\"}[$__interval])) by (status_code)"
    }
   ]
  },
  {
   "title": "[[handles]] timings",
   "type": "graph",
   "gridPos": { "h": 8, "w": 12, "x": 12, "y": 76 },
   "yaxes": [
    { "format": "short" }
   ],
   "targets": [
    {
     "expr": "histogram_quantile(0.95, sum(rate(starlette_requests_processing_time_seconds_bucket{job=\"qms\", path_template=\"[[handles]]\"}[$__interval])) by (le))"
    }
   ]
  },
  {
   "title": "[[handles]] http codes",
   "type": "graph",
   "gridPos": { "h": 8, "w": 12, "x": 0, "y": 84 },
   "yaxes": [
    { "format": "short" }
   ],
   "targets": [
    {
     "expr": "sum(rate(starlette_responses_total{job=\"qms\", path_template=\"[[handles]]\"}[$__interval])) by (status_code)"
    }
   ]
  },
  {
   "title": "[[handles]] timings",
   "type": "graph",
   "gridPos": { "h": 8, "w": 12, "x": 12, "y": 84 },
   "yaxes": [
    { "format": "short" }
   ],
   "targets": [
    {
     "expr": "histogram_quantile(0.95, sum(rate(starlette_requests_processing_time_seconds_bucket{job=\"qms\", path_template=\"[[handles]]\"}[$__interval])) by (le))"
    }
   ]
  },
  {
   "title": "[[handles]] http codes",
   "type": "graph",
   "gridPos": { "h": 8, "w": 12, "x": 0, "y": 92 },
   "yaxes": [
    { "format": "short" }
   ],
   "targets": [
    {
     "expr": "sum(rate(starlette_responses_total{job=\"qms\", path_template=\"[[handles]]\"}[$__interval])) by (status_code)"
    }
   ]
  },
  {
   "title": "[[handles]] timings",
   "type": "graph",
   "gridPos": { "h": 8, "w": 12, "x": 12, "y": 92 },
   "yaxes": [
    { "format": "short" }
   ],
   "targets": [
    {
     "expr": "histogram_quantile(0.95, sum(rate(starlette_requests_processing_time_seconds_bucket{job=\"qms\", path_template=\"[[handles]]\"}[$__interval])) by (le))"
    }
   ]
  },
  {
   "title": "[[handles]] http codes",
   "type": "graph",
   "gridPos": { "h": 8, "w": 12, "x": 0, "y": 100 },
   "yaxes": [
    { "format": "short" }
   ],
   "targets": [
    {
     "expr": "sum(rate(starlette_responses_total{job=\"qms\", path_template=\"[[handles]]\"}[$__interval])) by (status_code)"
    }
   ]
  },
  {
   "title": "[[handles]] timings",
   "type": "graph",
   "gridPos": { "h": 8, "w": 12, "x": 12, "y": 100 },
   "yaxes": [
    { "format": "short" }
   ],
   "targets": [
    {
     "expr": "histogram_quantile(0.95, sum(rate(starlette_requests_processing_time_seconds_bucket{job=\"qms\", path_template=\"[[handles]]\"}[$__interval])) by (le))"
    }
   ]
  },
  {
   "title": "[[handles]] http codes",
   "type": "graph",
   "gridPos": { "h": 8, "w": 12, "x": 0, "y": 108 },
   "yaxes": [
    { "format": "short" }
   ],
   "targets": [
    {
     "expr": "sum(rate(starlette_responses_total{job=\"qms\", path_template=\"[[handles]]\"}[$__interval])) by (status_code)"
    }
   ]
  },
  {
   "title": "[[handles]] timings",
   "type": "graph",
   "gridPos": { "h": 8, "w": 12, "x": 12, "y": 108 },
   "yaxes": [
    { "format": "short" }
   ],
   "targets": [
    {
     "expr": "histogram_quantile(0.95, sum(rate(starlette_requests_processing_time_seconds_bucket{job=\"qms\", path_template=\"[[handles]]\"}[$__interval])) by (le))"
    }
   ]
  },
  {
   "title": "[[handles]] http codes",
   "type": "graph",
   "gridPos": { "h": 8, "w": 12, "x": 0, "y": 116 },
   "yaxes": [
    { "format": "short" }
   ],
   "targets": [
    {
     "expr": "sum(rate(starlette_responses_total{job=\"qms\", path_template=\"[[handles]]\"}[$__interval])) by (status_code)"
    }
   ]
  },
  {
   "title": "[[handles]] timings",
   "type": "graph",
   "gridPos": { "h": 8, "w": 12, "x": 12, "y": 116 },
   "yaxes": [
    { "format": "short" }
   ],
   "targets": [
    {
     "expr": "histogram_quantile(0.95, sum(rate(starlette_requests_processing_time_seconds_bucket{job=\"qms\", path_template=\"[[handles]]\"}[$__interval])) by (le))"
    }
   ]
  },
  {
   "title": "[[handles]] http codes",
   "type": "graph",
   "gridPos": { "h": 8, "w": 12, "x": 0, "y": 124 },
   "yaxes": [
    { "format": "short" }
   ],
   "targets": [
    {
     "expr": "sum(rate(starlette_responses_total{job=\"qms\", path_template=\"[[handles]]\"}[$__interval])) by (status_code)"
    }
   ]
  },
  {
   "title": "[[handles]] timings",
   "type": "graph",
   "gridPos": { "h": 8, "w": 12, "x": 12, "y": 124 },
   "yaxes": [
    { "format": "short" }
   ],
   "targets": [
    {
     "expr": "histogram_quantile(0.95, sum(rate(starlette_requests_processing_time_seconds_bucket{job=\"qms\", path_template=\"[[handles]]\"}[$__interval])) by (le))"
    }
   ]
  },
  {
   "title": "[[handles]] http codes",
   "type": "graph",
   "gridPos": { "h": 8, "w": 12, "x": 0, "y": 132 },
   "yaxes": [
    { "format": "short" }
   ],
   "targets": [
    {
     "expr": "sum(rate(starlette_responses_total{job=\"qms\", path_template=\"[[handles]]\"}[$__interval])) by (status_code)"
    }
   ]
  },
  {
   "title": "[[handles]] timings",
   "type": "graph",
   "gridPos": { "h": 8, "w": 12, "x": 12, "y": 132 },
   "yaxes": [
    { "format": "short" }
   ],
   "targets": [
    {
     "expr": "histogram_quantile(0.95, sum(rate(starlette_requests_processing_time_seconds_bucket{job=\"qms\", path_template=\"[[handles]]\"}[$__interval])) by (le))"
    }
   ]
  },
  {
   "title": "[[handles]] http codes",
   "type": "graph",
   "gridPos": { "h": 8, "w": 12, "x": 0, "y": 140 },
   "yaxes": [
    { "format": "short" }
   ],
   "targets": [
    {
     "expr": "sum(rate(starlette_responses_total{job=\"qms\", path_template=\"[[handles]]\"}[$__interval])) by (status_code)"
    }
   ]
  },
  {
   "title": "[[handles]] timings",
   "type": "graph",
   "gridPos": { "h": 8, "w": 12, "x": 12, "y": 140 },
   "yaxes": [
    { "format": "short" }
   ],
   "targets": [
    {
     "expr": "histogram_quantile(0.95, sum(rate(starlette_requests_processing_time_seconds_bucket{job=\"qms\", path_template=\"[[handles]]\"}[$__interval])) by (le))"
    }
   ]
  },
  {
   "title": "[[handles]] http codes",
   "type": "graph",
   "gridPos": { "h": 8, "w": 12, "x": 0, "y": 148 },
   "yaxes": [
    { "format": "short" }
   ],
   "targets": [
    {
     "expr": "sum(rate(starlette_responses_total{job=\"qms\", path_template=\"[[handles]]\"}[$__interval])) by (status_code)"
    }
   ]
  },
  {
   "title": "[[handles]] timings",
   "type": "graph",
   "gridPos": { "h": 8, "w": 12, "x": 12, "y": 148 },
   "yaxes": [
    { "format": "short" }
   ],
   "targets": [
    {
     "expr": "histogram_quantile(0.95, sum(rate(starlette_requests_processing_time_seconds_bucket{job=\"qms\", path_template=\"[[handles]]\"}[$__interval])) by (le))"
    }
   ]
  },
  {
   "title": "[[handles]] http codes",
   "type": "graph",
   "gridPos": { "h": 8, "w": 12, "x": 0, "y": 156 },
   "yaxes": [
    { "format": "short" }
   ],
   "targets": [
    {
     "expr": "sum(rate(starlette_responses_total{job=\"qms\", path_template=\"[[handles]]\"}[$__interval])) by (status_code)"
    }
   ]
  },
  {
   "title": "[[handles]] timings",
   "type": "graph",
   "gridPos": { "h": 8, "w": 12, "x": 12, "y": 156 },
   "yaxes": [
    { "format": "short" }
   ],
   "targets": [
    {
     "expr": "histogram_quantile(0.95, sum(rate(starlette_requests_processing_time_seconds_bucket{job=\"qms\", path_template=\"[[handles]]\"}[$__interval])) by (le))"
    }
   ]
  },
  {
   "title": "[[handles]] http codes",
   "type": "graph",
   "gridPos": { "h": 8, "w": 12, "x": 0, "y": 164 },
   "yaxes": [
    { "format": "short" }
   ],
   "targets": [
    {
     "expr": "sum(rate(starlette_responses_total{job=\"qms\", path_template=\"[[handles]]\"}[$__interval])) by (status_code)"
    }
   ]
  },
  {
   "title": "[[handles]] timings",
   "type": "graph",
   "gridPos": { "h": 8, "w": 12, "x": 12, "y": 164 },
   "yaxes": [
    { "format": "short" }
   ],
   "targets": [
    {
     "expr": "histogram_quantile(0.95, sum(rate(starlette_requests_processing_time_seconds_bucket{job=\"qms\", path_template=\"[[handles]]\"}[$__interval])) by (le))"
    }
   ]
  },
  {
   "title": "[[handles]] http codes",
   "type": "graph",
   "gridPos": { "h": 8, "w": 12, "x": 0, "y": 172 },
   "yaxes": [
    { "format": "short" }
   ],
   "targets": [
    {
     "expr": "sum(rate(starlette_responses_total{job=\"qms\", path_template=\"[[handles]]\"}[$__interval])) by (status_code)"
    }
   ]
  },
  {
   "title": "[[handles]] timings",
   "type": "graph",
   "gridPos": { "h": 8, "w": 12, "x": 12, "y": 172 },
   "yaxes": [
    { "format": "short" }
   ],
   "targets": [
    {
     "expr": "histogram_quantile(0.95, sum(rate(starlette_requests_processing_time_seconds_bucket{job=\"qms\", path_template=\"[[handles]]\"}[$__interval])) by (le))"
    }
   ]
  },
  {
   "title": "[[handles]] http codes",
   "type": "graph",
   "gridPos": { "h": 8, "w": 12, "x": 0, "y": 180 },
   "yaxes": [
    { "format": "short" }
   ],
   "targets": [
    {
     "expr": "sum(rate(starlette_responses_total{job=\"qms\", path_template=\"[[handles]]\"}[$__interval])) by (status_code)"
    }
   ]
  },
  {
   "title": "[[handles]] timings",
   "type": "graph",
   "gridPos": { "h": 8, "w": 12, "x": 12, "y": 180 },
   "yaxes": [
    { "format": "short" }
   ],
   "targets": [
    {
     "expr": "histogram_quantile(0.95, sum(rate(starlette_requests_processing_time_seconds_bucket{job=\"qms\", path_template=\"[[handles]]\"}[$__interval])) by (le))"
    }
   ]
  },
  {
   "title": "[[handles]] http codes",
   "type": "graph",
   "gridPos": { "h": 8, "w": 12, "x": 0, "y": 188 },
   "yaxes": [
    { "format": "short" }
   ],
   "targets": [
    {
     "expr": "sum(rate(starlette_responses_total{job=\"qms\", path_template=\"[[handles]]\"}[$__interval])) by (status_code)"
    }
   ]
  },
  {
   "title": "[[handles]] timings",
   "type": "graph",
   "gridPos": { "h": 8, "w": 12, "x": 12, "y": 188 },
   "yaxes": [
    { "format": "short" }
   ],
   "targets": [
    {
     "expr": "histogram_quantile(0.95, sum(rate(starlette_requests_processing_time_seconds_bucket{job=\"qms\", path_template=\"[[handles]]\"}[$__interval])) by (le))"
    }
   ]
  }
 ]
}