# -*- coding: utf-8 -*-
# Generated by the protocol buffer compiler.  DO NOT EDIT!
# source: proto/service.proto
"""Generated protocol buffer code."""
from google.protobuf import descriptor as _descriptor
from google.protobuf import message as _message
from google.protobuf import reflection as _reflection
from google.protobuf import symbol_database as _symbol_database
# @@protoc_insertion_point(imports)

_sym_db = _symbol_database.Default()


from proto import timetable_pb2 as proto_dot_timetable__pb2
from proto import user_pb2 as proto_dot_user__pb2


DESCRIPTOR = _descriptor.FileDescriptor(
  name='proto/service.proto',
  package='qms',
  syntax='proto3',
  serialized_options=b'\n\016com.nevmem.qmsB\014ServiceProto',
  create_key=_descriptor._internal_create_key,
  serialized_pb=b'\n\x13proto/service.proto\x12\x03qms\x1a\x15proto/timetable.proto\x1a\x10proto/user.proto\"\xf6\x01\n\x0bServiceInfo\x12\n\n\x02id\x18\x01 \x01(\t\x12\x0c\n\x04name\x18\x02 \x01(\t\x12\x17\n\x0forganization_id\x18\x04 \x01(\t\x12\x1c\n\x14\x64\x65\x66\x61ult_waiting_time\x18\x05 \x01(\r\x12\x1c\n\x14\x61verage_waiting_time\x18\x06 \x01(\r\x12(\n\x04\x64\x61ta\x18\x03 \x03(\x0b\x32\x1a.qms.ServiceInfo.DataEntry\x12!\n\ttimetable\x18\x07 \x01(\x0b\x32\x0e.qms.Timetable\x1a+\n\tDataEntry\x12\x0b\n\x03key\x18\x01 \x01(\t\x12\r\n\x05value\x18\x02 \x01(\t:\x02\x38\x01\"5\n\x0fServiceInfoList\x12\"\n\x08services\x18\x01 \x03(\x0b\x32\x10.qms.ServiceInfo\"D\n\x07Service\x12\x1e\n\x04info\x18\x01 \x01(\x0b\x32\x10.qms.ServiceInfo\x12\x19\n\x06\x61\x64mins\x18\x03 \x03(\x0b\x32\t.qms.UserB\x1e\n\x0e\x63om.nevmem.qmsB\x0cServiceProtob\x06proto3'
  ,
  dependencies=[proto_dot_timetable__pb2.DESCRIPTOR,proto_dot_user__pb2.DESCRIPTOR,])




_SERVICEINFO_DATAENTRY = _descriptor.Descriptor(
  name='DataEntry',
  full_name='qms.ServiceInfo.DataEntry',
  filename=None,
  file=DESCRIPTOR,
  containing_type=None,
  create_key=_descriptor._internal_create_key,
  fields=[
    _descriptor.FieldDescriptor(
      name='key', full_name='qms.ServiceInfo.DataEntry.key', index=0,
      number=1, type=9, cpp_type=9, label=1,
      has_default_value=False, default_value=b"".decode('utf-8'),
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      serialized_options=None, file=DESCRIPTOR,  create_key=_descriptor._internal_create_key),
    _descriptor.FieldDescriptor(
      name='value', full_name='qms.ServiceInfo.DataEntry.value', index=1,
      number=2, type=9, cpp_type=9, label=1,
      has_default_value=False, default_value=b"".decode('utf-8'),
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      serialized_options=None, file=DESCRIPTOR,  create_key=_descriptor._internal_create_key),
  ],
  extensions=[
  ],
  nested_types=[],
  enum_types=[
  ],
  serialized_options=b'8\001',
  is_extendable=False,
  syntax='proto3',
  extension_ranges=[],
  oneofs=[
  ],
  serialized_start=273,
  serialized_end=316,
)

_SERVICEINFO = _descriptor.Descriptor(
  name='ServiceInfo',
  full_name='qms.ServiceInfo',
  filename=None,
  file=DESCRIPTOR,
  containing_type=None,
  create_key=_descriptor._internal_create_key,
  fields=[
    _descriptor.FieldDescriptor(
      name='id', full_name='qms.ServiceInfo.id', index=0,
      number=1, type=9, cpp_type=9, label=1,
      has_default_value=False, default_value=b"".decode('utf-8'),
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      serialized_options=None, file=DESCRIPTOR,  create_key=_descriptor._internal_create_key),
    _descriptor.FieldDescriptor(
      name='name', full_name='qms.ServiceInfo.name', index=1,
      number=2, type=9, cpp_type=9, label=1,
      has_default_value=False, default_value=b"".decode('utf-8'),
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      serialized_options=None, file=DESCRIPTOR,  create_key=_descriptor._internal_create_key),
    _descriptor.FieldDescriptor(
      name='organization_id', full_name='qms.ServiceInfo.organization_id', index=2,
      number=4, type=9, cpp_type=9, label=1,
      has_default_value=False, default_value=b"".decode('utf-8'),
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      serialized_options=None, file=DESCRIPTOR,  create_key=_descriptor._internal_create_key),
    _descriptor.FieldDescriptor(
      name='default_waiting_time', full_name='qms.ServiceInfo.default_waiting_time', index=3,
      number=5, type=13, cpp_type=3, label=1,
      has_default_value=False, default_value=0,
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      serialized_options=None, file=DESCRIPTOR,  create_key=_descriptor._internal_create_key),
    _descriptor.FieldDescriptor(
      name='average_waiting_time', full_name='qms.ServiceInfo.average_waiting_time', index=4,
      number=6, type=13, cpp_type=3, label=1,
      has_default_value=False, default_value=0,
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      serialized_options=None, file=DESCRIPTOR,  create_key=_descriptor._internal_create_key),
    _descriptor.FieldDescriptor(
      name='data', full_name='qms.ServiceInfo.data', index=5,
      number=3, type=11, cpp_type=10, label=3,
      has_default_value=False, default_value=[],
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      serialized_options=None, file=DESCRIPTOR,  create_key=_descriptor._internal_create_key),
    _descriptor.FieldDescriptor(
      name='timetable', full_name='qms.ServiceInfo.timetable', index=6,
      number=7, type=11, cpp_type=10, label=1,
      has_default_value=False, default_value=None,
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      serialized_options=None, file=DESCRIPTOR,  create_key=_descriptor._internal_create_key),
  ],
  extensions=[
  ],
  nested_types=[_SERVICEINFO_DATAENTRY, ],
  enum_types=[
  ],
  serialized_options=None,
  is_extendable=False,
  syntax='proto3',
  extension_ranges=[],
  oneofs=[
  ],
  serialized_start=70,
  serialized_end=316,
)


_SERVICEINFOLIST = _descriptor.Descriptor(
  name='ServiceInfoList',
  full_name='qms.ServiceInfoList',
  filename=None,
  file=DESCRIPTOR,
  containing_type=None,
  create_key=_descriptor._internal_create_key,
  fields=[
    _descriptor.FieldDescriptor(
      name='services', full_name='qms.ServiceInfoList.services', index=0,
      number=1, type=11, cpp_type=10, label=3,
      has_default_value=False, default_value=[],
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      serialized_options=None, file=DESCRIPTOR,  create_key=_descriptor._internal_create_key),
  ],
  extensions=[
  ],
  nested_types=[],
  enum_types=[
  ],
  serialized_options=None,
  is_extendable=False,
  syntax='proto3',
  extension_ranges=[],
  oneofs=[
  ],
  serialized_start=318,
  serialized_end=371,
)


_SERVICE = _descriptor.Descriptor(
  name='Service',
  full_name='qms.Service',
  filename=None,
  file=DESCRIPTOR,
  containing_type=None,
  create_key=_descriptor._internal_create_key,
  fields=[
    _descriptor.FieldDescriptor(
      name='info', full_name='qms.Service.info', index=0,
      number=1, type=11, cpp_type=10, label=1,
      has_default_value=False, default_value=None,
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      serialized_options=None, file=DESCRIPTOR,  create_key=_descriptor._internal_create_key),
    _descriptor.FieldDescriptor(
      name='admins', full_name='qms.Service.admins', index=1,
      number=3, type=11, cpp_type=10, label=3,
      has_default_value=False, default_value=[],
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      serialized_options=None, file=DESCRIPTOR,  create_key=_descriptor._internal_create_key),
  ],
  extensions=[
  ],
  nested_types=[],
  enum_types=[
  ],
  serialized_options=None,
  is_extendable=False,
  syntax='proto3',
  extension_ranges=[],
  oneofs=[
  ],
  serialized_start=373,
  serialized_end=441,
)

_SERVICEINFO_DATAENTRY.containing_type = _SERVICEINFO
_SERVICEINFO.fields_by_name['data'].message_type = _SERVICEINFO_DATAENTRY
_SERVICEINFO.fields_by_name['timetable'].message_type = proto_dot_timetable__pb2._TIMETABLE
_SERVICEINFOLIST.fields_by_name['services'].message_type = _SERVICEINFO
_SERVICE.fields_by_name['info'].message_type = _SERVICEINFO
_SERVICE.fields_by_name['admins'].message_type = proto_dot_user__pb2._USER
DESCRIPTOR.message_types_by_name['ServiceInfo'] = _SERVICEINFO
DESCRIPTOR.message_types_by_name['ServiceInfoList'] = _SERVICEINFOLIST
DESCRIPTOR.message_types_by_name['Service'] = _SERVICE
_sym_db.RegisterFileDescriptor(DESCRIPTOR)

ServiceInfo = _reflection.GeneratedProtocolMessageType('ServiceInfo', (_message.Message,), {

  'DataEntry' : _reflection.GeneratedProtocolMessageType('DataEntry', (_message.Message,), {
    'DESCRIPTOR' : _SERVICEINFO_DATAENTRY,
    '__module__' : 'proto.service_pb2'
    # @@protoc_insertion_point(class_scope:qms.ServiceInfo.DataEntry)
    })
  ,
  'DESCRIPTOR' : _SERVICEINFO,
  '__module__' : 'proto.service_pb2'
  # @@protoc_insertion_point(class_scope:qms.ServiceInfo)
  })
_sym_db.RegisterMessage(ServiceInfo)
_sym_db.RegisterMessage(ServiceInfo.DataEntry)

ServiceInfoList = _reflection.GeneratedProtocolMessageType('ServiceInfoList', (_message.Message,), {
  'DESCRIPTOR' : _SERVICEINFOLIST,
  '__module__' : 'proto.service_pb2'
  # @@protoc_insertion_point(class_scope:qms.ServiceInfoList)
  })
_sym_db.RegisterMessage(ServiceInfoList)

Service = _reflection.GeneratedProtocolMessageType('Service', (_message.Message,), {
  'DESCRIPTOR' : _SERVICE,
  '__module__' : 'proto.service_pb2'
  # @@protoc_insertion_point(class_scope:qms.Service)
  })
_sym_db.RegisterMessage(Service)


DESCRIPTOR._options = None
_SERVICEINFO_DATAENTRY._options = None
# @@protoc_insertion_point(module_scope)
