# -*- coding: utf-8 -*-
# Generated by the protocol buffer compiler.  DO NOT EDIT!
# source: proto/ticket.proto
"""Generated protocol buffer code."""
from google.protobuf import descriptor as _descriptor
from google.protobuf import message as _message
from google.protobuf import reflection as _reflection
from google.protobuf import symbol_database as _symbol_database
# @@protoc_insertion_point(imports)

_sym_db = _symbol_database.Default()


from proto import user_pb2 as proto_dot_user__pb2


DESCRIPTOR = _descriptor.FileDescriptor(
  name='proto/ticket.proto',
  package='qms',
  syntax='proto3',
  serialized_options=b'\n\016com.nevmem.qmsB\013TicketProto',
  create_key=_descriptor._internal_create_key,
  serialized_pb=b'\n\x12proto/ticket.proto\x12\x03qms\x1a\x10proto/user.proto\"\x88\x03\n\x06Ticket\x12\n\n\x02id\x18\x01 \x01(\t\x12\x0f\n\x07user_id\x18\x02 \x01(\t\x12\x12\n\nservice_id\x18\x03 \x01(\t\x12\x11\n\tticket_id\x18\x04 \x01(\t\x12\x17\n\x0forganization_id\x18\x08 \x01(\t\x12\x0e\n\x06window\x18\x0b \x01(\t\x12\x12\n\nenqueue_at\x18\x05 \x01(\x02\x12\x13\n\x0b\x61\x63\x63\x65pted_at\x18\t \x01(\x02\x12\x17\n\x04user\x18\x07 \x01(\x0b\x32\t.qms.User\x12 \n\x05state\x18\n \x01(\x0e\x32\x11.qms.Ticket.State\x12*\n\nresolution\x18\x0c \x01(\x0e\x32\x16.qms.Ticket.Resolution\"3\n\x05State\x12\x0b\n\x07WAITING\x10\x00\x12\x0e\n\nPROCESSING\x10\x01\x12\r\n\tPROCESSED\x10\x02\"L\n\nResolution\x12\x08\n\x04NONE\x10\x00\x12\x0c\n\x08SERVICED\x10\x01\x12\x10\n\x0cNOT_SERVICED\x10\x02\x12\n\n\x06KICKED\x10\x03\x12\x08\n\x04GONE\x10\x04\"`\n\nTicketInfo\x12\x1b\n\x06ticket\x18\x01 \x01(\x0b\x32\x0b.qms.Ticket\x12\x16\n\x0eremaining_time\x18\x02 \x01(\r\x12\x1d\n\x15people_in_front_count\x18\x03 \x01(\r\"*\n\nTicketList\x12\x1c\n\x07tickets\x18\x01 \x03(\x0b\x32\x0b.qms.TicketB\x1d\n\x0e\x63om.nevmem.qmsB\x0bTicketProtob\x06proto3'
  ,
  dependencies=[proto_dot_user__pb2.DESCRIPTOR,])



_TICKET_STATE = _descriptor.EnumDescriptor(
  name='State',
  full_name='qms.Ticket.State',
  filename=None,
  file=DESCRIPTOR,
  create_key=_descriptor._internal_create_key,
  values=[
    _descriptor.EnumValueDescriptor(
      name='WAITING', index=0, number=0,
      serialized_options=None,
      type=None,
      create_key=_descriptor._internal_create_key),
    _descriptor.EnumValueDescriptor(
      name='PROCESSING', index=1, number=1,
      serialized_options=None,
      type=None,
      create_key=_descriptor._internal_create_key),
    _descriptor.EnumValueDescriptor(
      name='PROCESSED', index=2, number=2,
      serialized_options=None,
      type=None,
      create_key=_descriptor._internal_create_key),
  ],
  containing_type=None,
  serialized_options=None,
  serialized_start=309,
  serialized_end=360,
)
_sym_db.RegisterEnumDescriptor(_TICKET_STATE)

_TICKET_RESOLUTION = _descriptor.EnumDescriptor(
  name='Resolution',
  full_name='qms.Ticket.Resolution',
  filename=None,
  file=DESCRIPTOR,
  create_key=_descriptor._internal_create_key,
  values=[
    _descriptor.EnumValueDescriptor(
      name='NONE', index=0, number=0,
      serialized_options=None,
      type=None,
      create_key=_descriptor._internal_create_key),
    _descriptor.EnumValueDescriptor(
      name='SERVICED', index=1, number=1,
      serialized_options=None,
      type=None,
      create_key=_descriptor._internal_create_key),
    _descriptor.EnumValueDescriptor(
      name='NOT_SERVICED', index=2, number=2,
      serialized_options=None,
      type=None,
      create_key=_descriptor._internal_create_key),
    _descriptor.EnumValueDescriptor(
      name='KICKED', index=3, number=3,
      serialized_options=None,
      type=None,
      create_key=_descriptor._internal_create_key),
    _descriptor.EnumValueDescriptor(
      name='GONE', index=4, number=4,
      serialized_options=None,
      type=None,
      create_key=_descriptor._internal_create_key),
  ],
  containing_type=None,
  serialized_options=None,
  serialized_start=362,
  serialized_end=438,
)
_sym_db.RegisterEnumDescriptor(_TICKET_RESOLUTION)


_TICKET = _descriptor.Descriptor(
  name='Ticket',
  full_name='qms.Ticket',
  filename=None,
  file=DESCRIPTOR,
  containing_type=None,
  create_key=_descriptor._internal_create_key,
  fields=[
    _descriptor.FieldDescriptor(
      name='id', full_name='qms.Ticket.id', index=0,
      number=1, type=9, cpp_type=9, label=1,
      has_default_value=False, default_value=b"".decode('utf-8'),
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      serialized_options=None, file=DESCRIPTOR,  create_key=_descriptor._internal_create_key),
    _descriptor.FieldDescriptor(
      name='user_id', full_name='qms.Ticket.user_id', index=1,
      number=2, type=9, cpp_type=9, label=1,
      has_default_value=False, default_value=b"".decode('utf-8'),
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      serialized_options=None, file=DESCRIPTOR,  create_key=_descriptor._internal_create_key),
    _descriptor.FieldDescriptor(
      name='service_id', full_name='qms.Ticket.service_id', index=2,
      number=3, type=9, cpp_type=9, label=1,
      has_default_value=False, default_value=b"".decode('utf-8'),
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      serialized_options=None, file=DESCRIPTOR,  create_key=_descriptor._internal_create_key),
    _descriptor.FieldDescriptor(
      name='ticket_id', full_name='qms.Ticket.ticket_id', index=3,
      number=4, type=9, cpp_type=9, label=1,
      has_default_value=False, default_value=b"".decode('utf-8'),
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      serialized_options=None, file=DESCRIPTOR,  create_key=_descriptor._internal_create_key),
    _descriptor.FieldDescriptor(
      name='organization_id', full_name='qms.Ticket.organization_id', index=4,
      number=8, type=9, cpp_type=9, label=1,
      has_default_value=False, default_value=b"".decode('utf-8'),
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      serialized_options=None, file=DESCRIPTOR,  create_key=_descriptor._internal_create_key),
    _descriptor.FieldDescriptor(
      name='window', full_name='qms.Ticket.window', index=5,
      number=11, type=9, cpp_type=9, label=1,
      has_default_value=False, default_value=b"".decode('utf-8'),
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      serialized_options=None, file=DESCRIPTOR,  create_key=_descriptor._internal_create_key),
    _descriptor.FieldDescriptor(
      name='enqueue_at', full_name='qms.Ticket.enqueue_at', index=6,
      number=5, type=2, cpp_type=6, label=1,
      has_default_value=False, default_value=float(0),
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      serialized_options=None, file=DESCRIPTOR,  create_key=_descriptor._internal_create_key),
    _descriptor.FieldDescriptor(
      name='accepted_at', full_name='qms.Ticket.accepted_at', index=7,
      number=9, type=2, cpp_type=6, label=1,
      has_default_value=False, default_value=float(0),
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      serialized_options=None, file=DESCRIPTOR,  create_key=_descriptor._internal_create_key),
    _descriptor.FieldDescriptor(
      name='user', full_name='qms.Ticket.user', index=8,
      number=7, type=11, cpp_type=10, label=1,
      has_default_value=False, default_value=None,
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      serialized_options=None, file=DESCRIPTOR,  create_key=_descriptor._internal_create_key),
    _descriptor.FieldDescriptor(
      name='state', full_name='qms.Ticket.state', index=9,
      number=10, type=14, cpp_type=8, label=1,
      has_default_value=False, default_value=0,
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      serialized_options=None, file=DESCRIPTOR,  create_key=_descriptor._internal_create_key),
    _descriptor.FieldDescriptor(
      name='resolution', full_name='qms.Ticket.resolution', index=10,
      number=12, type=14, cpp_type=8, label=1,
      has_default_value=False, default_value=0,
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      serialized_options=None, file=DESCRIPTOR,  create_key=_descriptor._internal_create_key),
  ],
  extensions=[
  ],
  nested_types=[],
  enum_types=[
    _TICKET_STATE,
    _TICKET_RESOLUTION,
  ],
  serialized_options=None,
  is_extendable=False,
  syntax='proto3',
  extension_ranges=[],
  oneofs=[
  ],
  serialized_start=46,
  serialized_end=438,
)


_TICKETINFO = _descriptor.Descriptor(
  name='TicketInfo',
  full_name='qms.TicketInfo',
  filename=None,
  file=DESCRIPTOR,
  containing_type=None,
  create_key=_descriptor._internal_create_key,
  fields=[
    _descriptor.FieldDescriptor(
      name='ticket', full_name='qms.TicketInfo.ticket', index=0,
      number=1, type=11, cpp_type=10, label=1,
      has_default_value=False, default_value=None,
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      serialized_options=None, file=DESCRIPTOR,  create_key=_descriptor._internal_create_key),
    _descriptor.FieldDescriptor(
      name='remaining_time', full_name='qms.TicketInfo.remaining_time', index=1,
      number=2, type=13, cpp_type=3, label=1,
      has_default_value=False, default_value=0,
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      serialized_options=None, file=DESCRIPTOR,  create_key=_descriptor._internal_create_key),
    _descriptor.FieldDescriptor(
      name='people_in_front_count', full_name='qms.TicketInfo.people_in_front_count', index=2,
      number=3, type=13, cpp_type=3, label=1,
      has_default_value=False, default_value=0,
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      serialized_options=None, file=DESCRIPTOR,  create_key=_descriptor._internal_create_key),
  ],
  extensions=[
  ],
  nested_types=[],
  enum_types=[
  ],
  serialized_options=None,
  is_extendable=False,
  syntax='proto3',
  extension_ranges=[],
  oneofs=[
  ],
  serialized_start=440,
  serialized_end=536,
)


_TICKETLIST = _descriptor.Descriptor(
  name='TicketList',
  full_name='qms.TicketList',
  filename=None,
  file=DESCRIPTOR,
  containing_type=None,
  create_key=_descriptor._internal_create_key,
  fields=[
    _descriptor.FieldDescriptor(
      name='tickets', full_name='qms.TicketList.tickets', index=0,
      number=1, type=11, cpp_type=10, label=3,
      has_default_value=False, default_value=[],
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      serialized_options=None, file=DESCRIPTOR,  create_key=_descriptor._internal_create_key),
  ],
  extensions=[
  ],
  nested_types=[],
  enum_types=[
  ],
  serialized_options=None,
  is_extendable=False,
  syntax='proto3',
  extension_ranges=[],
  oneofs=[
  ],
  serialized_start=538,
  serialized_end=580,
)

_TICKET.fields_by_name['user'].message_type = proto_dot_user__pb2._USER
_TICKET.fields_by_name['state'].enum_type = _TICKET_STATE
_TICKET.fields_by_name['resolution'].enum_type = _TICKET_RESOLUTION
_TICKET_STATE.containing_type = _TICKET
_TICKET_RESOLUTION.containing_type = _TICKET
_TICKETINFO.fields_by_name['ticket'].message_type = _TICKET
_TICKETLIST.fields_by_name['tickets'].message_type = _TICKET
DESCRIPTOR.message_types_by_name['Ticket'] = _TICKET
DESCRIPTOR.message_types_by_name['TicketInfo'] = _TICKETINFO
DESCRIPTOR.message_types_by_name['TicketList'] = _TICKETLIST
_sym_db.RegisterFileDescriptor(DESCRIPTOR)

Ticket = _reflection.GeneratedProtocolMessageType('Ticket', (_message.Message,), {
  'DESCRIPTOR' : _TICKET,
  '__module__' : 'proto.ticket_pb2'
  # @@protoc_insertion_point(class_scope:qms.Ticket)
  })
_sym_db.RegisterMessage(Ticket)

TicketInfo = _reflection.GeneratedProtocolMessageType('TicketInfo', (_message.Message,), {
  'DESCRIPTOR' : _TICKETINFO,
  '__module__' : 'proto.ticket_pb2'
  # @@protoc_insertion_point(class_scope:qms.TicketInfo)
  })
_sym_db.RegisterMessage(TicketInfo)

TicketList = _reflection.GeneratedProtocolMessageType('TicketList', (_message.Message,), {
  'DESCRIPTOR' : _TICKETLIST,
  '__module__' : 'proto.ticket_pb2'
  # @@protoc_insertion_point(class_scope:qms.TicketList)
  })
_sym_db.RegisterMessage(TicketList)


DESCRIPTOR._options = None
# @@protoc_insertion_point(module_scope)
