# -*- coding: utf-8 -*-
# Generated by the protocol buffer compiler.  DO NOT EDIT!
# source: proto/timetable.proto
"""Generated protocol buffer code."""
from google.protobuf import descriptor as _descriptor
from google.protobuf import message as _message
from google.protobuf import reflection as _reflection
from google.protobuf import symbol_database as _symbol_database
# @@protoc_insertion_point(imports)

_sym_db = _symbol_database.Default()




DESCRIPTOR = _descriptor.FileDescriptor(
  name='proto/timetable.proto',
  package='qms',
  syntax='proto3',
  serialized_options=b'\n\016com.nevmem.qmsB\016TimetableProto',
  create_key=_descriptor._internal_create_key,
  serialized_pb=b'\n\x15proto/timetable.proto\x12\x03qms\"\x86\x02\n\x0cWorkInterval\x12*\n\x07weekday\x18\x01 \x01(\x0e\x32\x19.qms.WorkInterval.WeekDay\x12*\n\x04\x66rom\x18\x02 \x01(\x0b\x32\x1c.qms.WorkInterval.TimeMarker\x12(\n\x02to\x18\x03 \x01(\x0b\x32\x1c.qms.WorkInterval.TimeMarker\x1a*\n\nTimeMarker\x12\x0c\n\x04hour\x18\x01 \x01(\r\x12\x0e\n\x06minute\x18\x02 \x01(\r\"H\n\x07WeekDay\x12\x07\n\x03MON\x10\x00\x12\x07\n\x03TUE\x10\x01\x12\x07\n\x03WED\x10\x02\x12\x07\n\x03THU\x10\x03\x12\x07\n\x03\x46RI\x10\x04\x12\x07\n\x03SAT\x10\x05\x12\x07\n\x03SUN\x10\x06\"-\n\tTimetable\x12 \n\x05works\x18\x01 \x03(\x0b\x32\x11.qms.WorkIntervalB \n\x0e\x63om.nevmem.qmsB\x0eTimetableProtob\x06proto3'
)



_WORKINTERVAL_WEEKDAY = _descriptor.EnumDescriptor(
  name='WeekDay',
  full_name='qms.WorkInterval.WeekDay',
  filename=None,
  file=DESCRIPTOR,
  create_key=_descriptor._internal_create_key,
  values=[
    _descriptor.EnumValueDescriptor(
      name='MON', index=0, number=0,
      serialized_options=None,
      type=None,
      create_key=_descriptor._internal_create_key),
    _descriptor.EnumValueDescriptor(
      name='TUE', index=1, number=1,
      serialized_options=None,
      type=None,
      create_key=_descriptor._internal_create_key),
    _descriptor.EnumValueDescriptor(
      name='WED', index=2, number=2,
      serialized_options=None,
      type=None,
      create_key=_descriptor._internal_create_key),
    _descriptor.EnumValueDescriptor(
      name='THU', index=3, number=3,
      serialized_options=None,
      type=None,
      create_key=_descriptor._internal_create_key),
    _descriptor.EnumValueDescriptor(
      name='FRI', index=4, number=4,
      serialized_options=None,
      type=None,
      create_key=_descriptor._internal_create_key),
    _descriptor.EnumValueDescriptor(
      name='SAT', index=5, number=5,
      serialized_options=None,
      type=None,
      create_key=_descriptor._internal_create_key),
    _descriptor.EnumValueDescriptor(
      name='SUN', index=6, number=6,
      serialized_options=None,
      type=None,
      create_key=_descriptor._internal_create_key),
  ],
  containing_type=None,
  serialized_options=None,
  serialized_start=221,
  serialized_end=293,
)
_sym_db.RegisterEnumDescriptor(_WORKINTERVAL_WEEKDAY)


_WORKINTERVAL_TIMEMARKER = _descriptor.Descriptor(
  name='TimeMarker',
  full_name='qms.WorkInterval.TimeMarker',
  filename=None,
  file=DESCRIPTOR,
  containing_type=None,
  create_key=_descriptor._internal_create_key,
  fields=[
    _descriptor.FieldDescriptor(
      name='hour', full_name='qms.WorkInterval.TimeMarker.hour', index=0,
      number=1, type=13, cpp_type=3, label=1,
      has_default_value=False, default_value=0,
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      serialized_options=None, file=DESCRIPTOR,  create_key=_descriptor._internal_create_key),
    _descriptor.FieldDescriptor(
      name='minute', full_name='qms.WorkInterval.TimeMarker.minute', index=1,
      number=2, type=13, cpp_type=3, label=1,
      has_default_value=False, default_value=0,
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      serialized_options=None, file=DESCRIPTOR,  create_key=_descriptor._internal_create_key),
  ],
  extensions=[
  ],
  nested_types=[],
  enum_types=[
  ],
  serialized_options=None,
  is_extendable=False,
  syntax='proto3',
  extension_ranges=[],
  oneofs=[
  ],
  serialized_start=177,
  serialized_end=219,
)

_WORKINTERVAL = _descriptor.Descriptor(
  name='WorkInterval',
  full_name='qms.WorkInterval',
  filename=None,
  file=DESCRIPTOR,
  containing_type=None,
  create_key=_descriptor._internal_create_key,
  fields=[
    _descriptor.FieldDescriptor(
      name='weekday', full_name='qms.WorkInterval.weekday', index=0,
      number=1, type=14, cpp_type=8, label=1,
      has_default_value=False, default_value=0,
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      serialized_options=None, file=DESCRIPTOR,  create_key=_descriptor._internal_create_key),
    _descriptor.FieldDescriptor(
      name='from', full_name='qms.WorkInterval.from', index=1,
      number=2, type=11, cpp_type=10, label=1,
      has_default_value=False, default_value=None,
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      serialized_options=None, file=DESCRIPTOR,  create_key=_descriptor._internal_create_key),
    _descriptor.FieldDescriptor(
      name='to', full_name='qms.WorkInterval.to', index=2,
      number=3, type=11, cpp_type=10, label=1,
      has_default_value=False, default_value=None,
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      serialized_options=None, file=DESCRIPTOR,  create_key=_descriptor._internal_create_key),
  ],
  extensions=[
  ],
  nested_types=[_WORKINTERVAL_TIMEMARKER, ],
  enum_types=[
    _WORKINTERVAL_WEEKDAY,
  ],
  serialized_options=None,
  is_extendable=False,
  syntax='proto3',
  extension_ranges=[],
  oneofs=[
  ],
  serialized_start=31,
  serialized_end=293,
)


_TIMETABLE = _descriptor.Descriptor(
  name='Timetable',
  full_name='qms.Timetable',
  filename=None,
  file=DESCRIPTOR,
  containing_type=None,
  create_key=_descriptor._internal_create_key,
  fields=[
    _descriptor.FieldDescriptor(
      name='works', full_name='qms.Timetable.works', index=0,
      number=1, type=11, cpp_type=10, label=3,
      has_default_value=False, default_value=[],
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      serialized_options=None, file=DESCRIPTOR,  create_key=_descriptor._internal_create_key),
  ],
  extensions=[
  ],
  nested_types=[],
  enum_types=[
  ],
  serialized_options=None,
  is_extendable=False,
  syntax='proto3',
  extension_ranges=[],
  oneofs=[
  ],
  serialized_start=295,
  serialized_end=340,
)

_WORKINTERVAL_TIMEMARKER.containing_type = _WORKINTERVAL
_WORKINTERVAL.fields_by_name['weekday'].enum_type = _WORKINTERVAL_WEEKDAY
_WORKINTERVAL.fields_by_name['from'].message_type = _WORKINTERVAL_TIMEMARKER
_WORKINTERVAL.fields_by_name['to'].message_type = _WORKINTERVAL_TIMEMARKER
_WORKINTERVAL_WEEKDAY.containing_type = _WORKINTERVAL
_TIMETABLE.fields_by_name['works'].message_type = _WORKINTERVAL
DESCRIPTOR.message_types_by_name['WorkInterval'] = _WORKINTERVAL
DESCRIPTOR.message_types_by_name['Timetable'] = _TIMETABLE
_sym_db.RegisterFileDescriptor(DESCRIPTOR)

WorkInterval = _reflection.GeneratedProtocolMessageType('WorkInterval', (_message.Message,), {

  'TimeMarker' : _reflection.GeneratedProtocolMessageType('TimeMarker', (_message.Message,), {
    'DESCRIPTOR' : _WORKINTERVAL_TIMEMARKER,
    '__module__' : 'proto.timetable_pb2'
    # @@protoc_insertion_point(class_scope:qms.WorkInterval.TimeMarker)
    })
  ,
  'DESCRIPTOR' : _WORKINTERVAL,
  '__module__' : 'proto.timetable_pb2'
  # @@protoc_insertion_point(class_scope:qms.WorkInterval)
  })
_sym_db.RegisterMessage(WorkInterval)
_sym_db.RegisterMessage(WorkInterval.TimeMarker)

Timetable = _reflection.GeneratedProtocolMessageType('Timetable', (_message.Message,), {
  'DESCRIPTOR' : _TIMETABLE,
  '__module__' : 'proto.timetable_pb2'
  # @@protoc_insertion_point(class_scope:qms.Timetable)
  })
_sym_db.RegisterMessage(Timetable)


DESCRIPTOR._options = None
# @@protoc_insertion_point(module_scope)
