name: build_push_docker

on: [ push ]

jobs:
  build_push:
    name: "Build and push docker of push microservice"
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@master
      - name: set up JDK 1.8
        uses: actions/setup-java@v1
        with:
          java-version: 1.8
      - name: "Build docker"
        run: cd push/docker/ && ./build.sh
      - name: "Login to registry"
        uses: docker/login-action@v1
        with:
          registry: cr.yandex
          username: json_key
          password: ${{ secrets.REGISTRY_SECRET }}
      - name: "Push"
        run: docker push cr.yandex/crp59su1rb652ia7ojk8/push:$(git rev-parse HEAD)
