name: build_docker

on: [push]

jobs:
  build:
    name: "Build and push docker"
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@master
      - name: "Login to registry"
        uses: docker/login-action@v1
        with:
          registry: cr.yandex
          username: json_key
          password: ${{ secrets.REGISTRY_SECRET }}
      - name: "Build docker"
        run: cd server/docker/ && ./build.sh
      - name: "Push"
        run: docker push cr.yandex/crp59su1rb652ia7ojk8/init:$(git rev-parse HEAD)
