on: [ push ]


name: server_tests

jobs:
  test:
    name: Server units
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@master
      - name: Install deps
        run: server/tests/helpers/prepare_env.sh
      - name: Run tests
        run: pytest ./server/app/tests
